routes/admin.php
<?php

Route::group(['middleware' => ['auth','role:1'], 'prefix' => 'admin'], function(){

    Route::get('dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');

    Route::resource('empresa', 'Admin\EmpresaController');
    Route::resource('areas', 'Admin\AreasController');
    Route::resource('categorias', 'Admin\CategoriaController');
    Route::resource('subcategorias', 'Admin\SubCategoriasController');

    Route::resource('subareas', 'Admin\SubareasController');
    Route::resource('usuarios', 'Admin\UsuarioController');
 	
 	/*Controlador de los inventarios*/
    Route::resource('inventarios', 'Admin\InventarioAdminController');
    Route::get('producto', 'Admin\InventarioAdminController@producto')->name('admin.producto');

    /*Controlador de las compras*/
    Route::resource('compra', 'Admin\ComprasAdminController');
    Route::post('compra/proveedor', 'Admin\ComprasAdminController@proveedor')->name('compra.proveedor');
    Route::post('compra/productos', 'Admin\ComprasAdminController@productos')->name('compra.productos');

    Route::get('admininventariocomprarealizadas', 'Admin\ComprasAdminController@realizadas')->name('admin.inventario.compras.realizadas');
    Route::get('admininventariocomprasautorizadas', 'Admin\ComprasAdminController@autorizadas')->name('admin.inventario.compras.autorizadas');
    Route::get('admininventariocomprasrechazadas', 'Admin\ComprasAdminController@rechazadas')->name('admin.inventario.compras.rechazadas');

    /*Controlador de los presupuestos*/

    Route::resource('presupuestoadmin', 'Admin\PresupuestoAdminController');

    Route::get('presupuestocreados', 'Admin\PresupuestoAdminController@presupuestocreados')->name('admin.presupuesto.presupuestocreados');

    Route::get('presupuestoautorizado', 'Admin\PresupuestoAdminController@presupuestoautorizado')->name('admin.presupuesto.presupuestoautorizado');

    Route::get('presupuestorechazados', 'Admin\PresupuestoAdminController@presupuestorechazados')->name('admin.presupuesto.presupuestorechazados');

    Route::resource('proveedor', 'Admin\ProveedoresAdminController');

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
/*
	---Apis
*/
Route::get('area/{id}', 'HomeController@getArea');
Route::get('subarea/{id}', 'HomeController@getSubArea');
Route::get('/providers/{id}', 'HomeController@getProviders');
Route::get('/productos/{id}', 'HomeController@getProductos');
Route::get('/categorias/{id}', 'HomeController@getCategorias');
Route::get('/productostiquets/{id}/{presupuesto}', 'HomeController@getProductosTiquets');



require __DIR__ . '/admin.php';
require __DIR__ . '/gerencia.php';
require __DIR__ . '/almacenista.php';
require __DIR__ . '/encargado.php';

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    protected $table = 'areas';

    protected $fillable = [
        'clave','nombre', 'empresa_id'
    ];

     public function empresa()
    {
        return $this->belongsTo(Empresa::class, 'empresa_id');
    }
}

app/Http/Controllers/Admin/AreasController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Area;
use App\Empresa;

class AreasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $areas = Area::all();
        $empresa = Empresa::all();
        return view('admin.areas.index', compact('areas','empresa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
                'clave' => 'required|unique:areas',
                'nombre' => 'required',
                'empresa_id' => 'required'
            ]
        );
       $area = Area::create([
            'clave' => $request->get('clave'),
            'nombre' => $request->get('nombre'),
            'empresa_id' => $request->get('empresa_id'),

        ]);

        alert()->success('El area ha sido creado correctamente.', 'Area creada');
        return redirect()->route('areas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       $this->validate($request,[
            'nombre' => 'required',
            'empresa_id' => 'required'
        ]);
        $areas = Area::find($id)->update($request->except(['_method', '_token']));
        alert()->success('El area ha sido actualizada correctamente.', 'Area actualizada');
        return redirect()->route('areas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/areas/create.blade.php
<div class="modal" id="crear_area">
    <div class="modal__content modal__content--xl">
        <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                Crear nueva areas
            </h2>
            <!--
            	<button class="button border items-center text-gray-700 hidden sm:flex"> <i data-feather="file" class="w-4 h-4 mr-2"></i> Download Docs </button>
	            <div class="dropdown relative sm:hidden">
	                <a class="dropdown-toggle w-5 h-5 block" href="javascript:;"> <i data-feather="more-horizontal" class="w-5 h-5 text-gray-700"></i> </a>
	                <div class="dropdown-box mt-5 absolute w-40 top-0 right-0 z-20">
	                    <div class="dropdown-box__content box p-2">
	                        <a href="javascript:;" class="flex items-center p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md"> <i data-feather="file" class="w-4 h-4 mr-2"></i> Download Docs </a>
	                    </div>
	                </div>
	            </div>
        	-->
        </div>
        <form method="POST" action="{{ route('areas.store') }}"  role="form">
            {{ csrf_field() }}
            <div class="p-5 grid grid-cols-12 gap-4 row-gap-3">
                <div class="col-span-12 sm:col-span-4 @if ($errors->has('clave')) has-error @endif">
                    <label class="font-medium text-base mr-auto" for="clave">Clave:</label>
                    <input type="text" class="input w-full border mt-2 flex-1" name="clave" id="clave" aria-describedby="helpClave">
                    <span id="helpClave" class="help-block">
                        @if ($errors->has('clave'))
                            @foreach($errors->get('clave') as $message)
                                @if(!$loop->first) / @endif
                                {{ $message }}
                            @endforeach
                        @endif
                    </span>
                </div>
                <div class="col-span-12 sm:col-span-4 @if ($errors->has('nombre')) has-error @endif">
                    <label class="font-medium text-base mr-auto" for="nombre">Nombre del area:</label>
                    <input type="text" class="input w-full border mt-2 flex-1" name="nombre" id="nombre" aria-describedby="helpNombre">
                    <span id="helpNombre" class="help-block">
                        @if ($errors->has('nombre'))
                            @foreach($errors->get('nombre') as $message)
                                @if(!$loop->first) / @endif
                                {{ $message }}
                            @endforeach
                        @endif
                    </span>
                </div>
                <div class="col-span-12 sm:col-span-4 @if ($errors->has('empresa_id')) has-error @endif">
                    <label class="font-medium text-base mr-auto" for="empresa_id">Nombre de la empresa:</label>
                    <select class="input w-full border mt-2 flex-1" id="empresa_id" name="empresa_id">
                    		<option value="">Selecciona una opcion</option>
                        @foreach($empresa as $empresas)
                            <option value="{{$empresas->id}}">{{$empresas->nombre}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-span-12 sm:col-span-12">
                </div>
            </div>
            <div class="px-5 py-3 text-right border-t border-gray-200">
                <button type="button" data-dismiss="modal" class="button w-20 border text-gray-700 mr-1">Cancelar</button>
                <button class="button w-20 bg-theme-1 text-white">Guardar</button>
            </div>
        </form>
    </div>
</div>

resources/views/admin/areas/index.blade.php
@extends('layouts/app')
@section('title', 'Departamento')
@section('content')
<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Departamento
    </h2>
    <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
        <a class="button text-white bg-theme-1 shadow-md mr-2" href="javascript:;" data-toggle="modal" data-target="#crear_area" >Crear nuevo Departamento</a>
        @include('admin.areas.create')
        <!-- 
        <div class="dropdown relative ml-auto sm:ml-0">
            <button class="dropdown-toggle button px-2 box text-gray-700">
                <span class="w-5 h-5 flex items-center justify-center"> <i class="w-4 h-4" data-feather="plus"></i> </span>
            </button>
            <div class="dropdown-box mt-10 absolute w-40 top-0 right-0 z-20">
                <div class="dropdown-box__content box p-2">
                    <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md"> <i data-feather="file-plus" class="w-4 h-4 mr-2"></i> New Category </a>
                    <a href="" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md"> <i data-feather="users" class="w-4 h-4 mr-2"></i> New Group </a>
                </div>
            </div> 
        </div>
        -->
    </div>
</div><br><br>

 <div class="overflow-x-auto">
     <table class="table">
         <thead>
             <tr class="bg-gray-700 text-white" >
                 <th class="border-b-2 whitespace-no-wrap">Id</th>
                 <th class="border-b-2 whitespace-no-wrap">Clave</th>
                 <th class="border-b-2 whitespace-no-wrap">Nombre del Departamento</th>
                 <th class="border-b-2 whitespace-no-wrap">Nombre de la empresa</th>
                 <th class="border-b-2 whitespace-no-wrap">Opciones</th>
             </tr>
         </thead>
         <tbody>
            @foreach($areas as $area)
             <tr>
                 <td class="border-b whitespace-no-wrap">{{$area->id}}</td>
                 <td class="border-b whitespace-no-wrap">{{$area->clave}}</td>
                 <td class="border-b whitespace-no-wrap">{{$area->nombre}}</td>
                 <td class="border-b whitespace-no-wrap">{{$area->empresa->nombre}}</td>
                 <td class="border-b whitespace-no-wrap">
                    <div class="flex">
                        <a class="flex items-center mr-3"data-toggle="modal" data-target="#edit-area{{$area->id}}"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Editar </a>
                        
                    </div>
                </td>
                 @include('admin.areas.updated')                
             </tr>
            @endforeach 
         
         </tbody>
     </table>
 </div>

@endsection

resources/views/admin/areas/updated.blade.php
<div class="modal" id="edit-area{{$area->id}}">
    <div class="modal__content modal__content--xl">
        <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                Actualizacion del area {{$area->nombre}}
            </h2>
            <button class="button border items-center text-gray-700 hidden sm:flex"> <i data-feather="file" class="w-4 h-4 mr-2"></i> Download Docs </button>
            <div class="dropdown relative sm:hidden">
                <a class="dropdown-toggle w-5 h-5 block" href="javascript:;"> <i data-feather="more-horizontal" class="w-5 h-5 text-gray-700"></i> </a>
                <div class="dropdown-box mt-5 absolute w-40 top-0 right-0 z-20">
                    <div class="dropdown-box__content box p-2">
                        <a href="javascript:;" class="flex items-center p-2 transition duration-300 ease-in-out bg-white hover:bg-gray-200 rounded-md"> <i data-feather="file" class="w-4 h-4 mr-2"></i> Download Docs </a>
                    </div>
                </div>
            </div>
        </div>
        {!! Form::open(['route' => ['areas.update', $area->id], 'method' => 'PUT']) !!}
        {{ csrf_field() }}
            <div class="p-5 grid grid-cols-12 gap-4 row-gap-3">
                <div class="col-span-12 sm:col-span-4 @if ($errors->has('clave')) has-error @endif">
                    <label class="font-medium text-base mr-auto" for="clave">Clave:</label>
                    <input type="text" class="input w-full border mt-2 flex-1" name="clave" id="clave" value="{{ $area->clave }}" aria-describedby="helpClave">
                    <span id="helpClave" class="help-block">
                        @if ($errors->has('clave'))
                            @foreach($errors->get('clave') as $message)
                                @if(!$loop->first) / @endif
                                {{ $message }}
                            @endforeach
                        @endif
                    </span>
                </div>
                <div class="col-span-12 sm:col-span-4 @if ($errors->has('nombre')) has-error @endif">
                    <label class="font-medium text-base mr-auto" for="nombre">Nombre del area:</label>
                    <input type="text" class="input w-full border mt-2 flex-1" name="nombre" id="nombre" value="{{ $area->nombre }}" aria-describedby="helpNombre">
                    <span id="helpNombre" class="help-block">
                        @if ($errors->has('nombre'))
                            @foreach($errors->get('nombre') as $message)
                                @if(!$loop->first) / @endif
                                {{ $message }}
                            @endforeach
                        @endif
                    </span>
                </div>
                <div class="col-span-12 sm:col-span-4 @if ($errors->has('empresa_id')) has-error @endif">
                    <label class="font-medium text-base mr-auto" for="empresa_id">Nombre de la empresa:</label>
                    <select class="input w-full border mt-2 flex-1" id="empresa_id" name="empresa_id">
                        @foreach($empresa as $empresas)
                            <option value="{{$empresas->id}}" @if($area->empresa_id == $empresas->id) selected="selected" @endif>{{$empresas->nombre}}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-span-12 sm:col-span-12">
                </div>
            </div>
            <div class="px-5 py-3 text-right border-t border-gray-200">
                <button type="button" data-dismiss="modal" class="button w-20 border text-gray-700 mr-1">Cancelar</button>
                <button class="button w-20 bg-theme-1 text-white">Guardar</button>
            </div>
        {!! Form::close()!!}
    </div>
</div>